# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Moin - an event-driven microservice application-server written in Node.JS
email: torben.hartmann@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Moin.js is a microservice Application server, written In Node.js
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://moinjs.github.io" # the base hostname & protocol for your site
twitter_username: torbenhartmann
github_username:  moinjs

# Build settings
markdown: kramdown
collections:
  - docs